# Generated by Django 3.0.4 on 2020-03-20 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20200319_2031'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='dept',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='registration_number',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
    ]
