# Generated by Django 3.0.4 on 2020-05-05 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20200320_1502'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='event_ids',
            field=models.TextField(null=True),
        ),
    ]
