# Generated by Django 3.0.4 on 2020-05-16 14:36

import django.core.validators
from django.db import migrations, models
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20200514_2331'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='passout_year',
            field=models.PositiveIntegerField(default=2020, validators=[django.core.validators.MinValueValidator(1984), users.models.max_value_current_year]),
        ),
    ]
