# Generated by Django 2.2.1 on 2020-03-10 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='category',
            field=models.CharField(choices=[('INF', 'Infrastructure'), ('GEN', 'Generic'), ('CUR', 'Curriculum')], default='GEN', max_length=3),
        ),
    ]
