# Generated by Django 3.0.4 on 2020-03-19 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='dept',
            field=models.CharField(default=None, max_length=120),
        ),
        migrations.AddField(
            model_name='profile',
            name='registration_number',
            field=models.CharField(default=None, max_length=12),
        ),
    ]
