# Generated by Django 3.0.4 on 2020-05-14 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20200514_2300'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='dept',
            field=models.CharField(choices=[('', ''), ('COMPUTER SCIENCE AND ENGINEERING', 'COMPUTER SCIENCE AND ENGINEERING'), ('INFORMATION TECHNOLOGY', 'INFORMATION TECHNOLOGY'), ('ELECTRONICS AND COMMUNICATION ENGINEERING', 'ELECTRONICS AND COMMUNICATION ENGINEERING'), ('ELECTRICAL AND ELECTRONIC ENGINEERING', 'ELECTRICAL AND ELECTRONIC ENGINEERING'), ('MECHANICAL ENGINEERING', 'MECHANICAL ENGINEERING'), ('CIVIL ENGINEERING', 'CIVIL ENGINEERING')], default='', max_length=120, null=True),
        ),
    ]
